### ISSUE TITLE
Separate container for the WebServer

### ISSUE THREAD

**Issue by JaragonCR** [nebhead/PiFire#146]
Have you considered separating the web server, my idea would be it can run on a container and acquire data from the pifire, that way you can store your old sessions regardless of the SD. A lot of the people using this would have already a docker or vm environment l, so pushing numbers instead of the complete website will also allow for wifi signal to be less critical.

**Comment by nebhead** [comment]
This is an interesting idea.  Will consider this in the future.  For now, the implementation relies on the API being part of the webserver.
