### ISSUE TITLE
ratelimitingfilter

### ISSUE THREAD

**Issue by G4KCM** [nebhead/PiFire#163]
Just to mention that presently if the development branch is installed by the script the control side hangs on startup due to missing the python module ratelimitingfilter.  After manually installing this it runs up Ok.

Cheers  
Clive

**Comment by nebhead** [comment]
Thanks for the heads up!  I will add this to the installer and updater to make sure it gets added in both cases.

**Comment by G4KCM** [comment]
👍 and my sincere thanks for all your work!

**Comment by G4KCM** [comment]
👍 and my sincere thanks for the great work you are doing on PiFire!

**Comment by nebhead** [comment]
Thanks again and this should be fixed in the latest development branch push.
