### ISSUE TITLE
PWM Temp Control icon missing from control bar after entering Hold mode

### ISSUE THREAD

**Issue by ghandye** [nebhead/PiFire#185]
**Describe the bug**
When PWM Temp Control is enabled and the user transitions to Hold mode (e.g. from Startup mode), the PWM Temp Control icon is initially missing from the control bar. Manually refreshing the page makes it appear.

**To Reproduce**

- Configure PWM grill platform
- Enable Settings > Theme > Show Control Panel on Most Pages
- (possibly not required for repro) Enable Settings > PWM Settings > PWM Temp Control Settings > Temp Control Enabled by Default

Required actions:
- Click Startup on control bar, and confirm startup
- Click Hold on control bar, and enter a temp (e.g. 250) and click Set (note that you don't have to actually go through full Startup to reproduce, you can just go from Startup to Hold mode on a cold grill to test)
- Grill enters hold mode, and control bar changes to reflect temperature

- (BUG) Notice how Smoke Plus toggle icon shows up on control bar, but PWM Temp Control icon does not
![image](https://github.com/nebhead/PiFire/assets/13396513/9e033c13-0aeb-4bd5-818e-e7d822de6573)

- (Workaround) Refresh browser page (e.g. hit F5), PWM Temp icon now shows up
![image](https://github.com/nebhead/PiFire/assets/13396513/2027555b-151d-4268-949d-223cf3723a0c)

**Expected behavior**
PWM Temp Control icon should immediately show up on bottom control bar when entering Hold mode if grill supports PWM.

**Screenshots**
(See inline above)

**PiFire Version:**
PiFire Version: 1.7.0
PiFire Build: 54

**Additional context**
Reproduced on Safari on iPhone, and Firefox on Windows.
Not a huge deal, refreshing the page fixes it.

**Comment by nebhead** [comment]
OK, I think I have it fixed now but want to confirm the behavior that this button should not show up in Smoke mode.
