### ISSUE TITLE
Pellet-Manager calculate pallets wrong

### ISSUE THREAD

**Issue by benixs** [nebhead/PiFire#199]
On the Pellet-Manager it displays a user over a tonne of Pellets. 
I have a feed Rate of 0.9g/s maybe it calculate it wrong. Then  Prime ist on 20grams and it calculate 361kg...

Prime in  Data 22s and 20 gramm

![Screenshot_20240929-172710](https://github.com/user-attachments/assets/e47aea50-9a66-4c1f-9e93-212aeeccea56)

**PiFire Version:**
 - Version 1.8.1

**Comment by nebhead** [comment]
That sure looks like a bug!  I think it's actually the time that is calculated incorrectly in the metrics log.  I'll look into this and hopefully get this one squashed.  Thanks for the issue submission!

**Comment by nebhead** [comment]
Did you by any chance adjust the time/date during the run?  

Start time was: 
![image](https://github.com/user-attachments/assets/f7b176d4-e6c3-45e2-9305-3d3230348d90)

End time was: 
![image](https://github.com/user-attachments/assets/d36cb4eb-d793-4641-ac32-a8d571cbbeaf)

**Comment by nebhead** [comment]
I'm going to close this.  Feel free to open again if you want to continue to debug.
