### ISSUE TITLE
Problem after SW update and re-install

### ISSUE THREAD

**Issue by thomasstrach** [nebhead/PiFire#207]
Hi, 

as performed several times before I used the update function to get the latest version on my RPi controller.
Unfortunately it ended up with 2 error messages:
"Unable to reach Redis database. You may need to reinstall PiFire or enable rdis-server.
The control process did not respond to a request and may be stopped.

So I reinstalled PiFire with: 
curl https://raw.githubusercontent.com/nebhead/pifire/main/auto-install/install.sh | bash

and ended up in a different error on supervisor page:
Webapp fatal error.
can't find command '/usr/local/bin/pifire/bin/gunicorn'
![image](https://github.com/user-attachments/assets/d14fb995-4d3a-4e19-897d-6d6abb3953b1)

and this error log message:

n /usr/local/lib/python3.9/dist-packages (from adafruit-circuitpython-typing->Adafruit-Blinka->adafruit-circuitpython-ads1x15) (1.14.0)
Return Code: 0
Reading package lists...
Building dependency tree...
Reading state information...
python3-smbus is already the newest version (4.2-1+b1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Return Code: 0
command output: PiFire Board Configuration Tool v1.0.0
command output: Ben Parmeter - 2024 - MIT License
command output: --help, -h for command details
command output: 
command output: Results:
command output: - Setting the 1Wire pin: SUCCESS
command output: - Enabling SPI: SUCCESS
command output: - Enabling I2C: SUCCESS
command output: - Attempting to append data to /etc/modules:  SUCCESS (appending file /etc/modules)
command output: PiFire Board Configuration Tool v1.0.0
command output: Ben Parmeter - 2024 - MIT License
command output: --help, -h for command details
command output: 
command output: Results:
command output: - Enabling SPI: SUCCESS

**Comment by nebhead** [comment]
It sounds from your description that at least the second time you installed pifire, it didn't install correctly.  Did you wipe the SDCard before running the installation script?

**Comment by thomasstrach** [comment]
Hi,
Reinstalling was not that easy as the raspberry did not boot with network connectivity. Nevertheless after new image and re-installing latest version the error messages are gone but for whatever reason the auger does not work anymore. All other Relais are working fine, only the auger output is not providing any signal. 
Do you have any idea? 
Even in manual mode I can see the icon on the display but the relay gets no signal.
Any special config at raspberry needed?

**Comment by thomasstrach** [comment]
I am running HW board ver 2.00 with a raspberry zero 2W, mechanical Relais Modul, SPI Display, Encoder Button and vl53l0x sensor. Do you need any log file?

**Comment by nebhead** [comment]
Are you now on the latest PiFire (main branch)?  v1.8.x? 

In the configuration wizard, are you selecting the 2.00a PCB? 

![image](https://github.com/user-attachments/assets/63b85e16-1315-480e-9039-3148020839e0)

Can get the settings.json file (let me know if you need help getting this) and post the platform configuration section?   It should look something like this (yours will have different values):

```json
  "platform": {
    "buttonslevel": "HIGH",
    "current": "custom",
    "dc_fan": true,
    "devices": {
      "display": {
        "dc": 24,
        "led": 5,
        "rst": 25
      },
      "distance": {
        "echo": 27,
        "trig": 23
      },
      "input": {
        "down_dt": 20,
        "enter_sw": 21,
        "up_clk": 16
      }
    },
    "inputs": {
      "selector": 17,
      "shutdown": 17
    },
    "outputs": {
      "auger": 14,
      "dc_fan": 26,
      "fan": 15,
      "igniter": 18,
      "power": 4,
      "pwm": 13
    },
    "real_hw": false,
    "standalone": true,
    "system": {
      "1WIRE": 6,
      "SPI0": {
        "CE0": 8,
        "CE1": 7
      }
    },
    "system_type": "prototype",
    "triggerlevel": "HIGH"
  }
```

**Comment by thomasstrach** [comment]
Hi,

 

yes I am on latest version now:

System Update (Current Version: 1.8.8)

 

I have chosen the Version 2.00a PCB during config.

The other 3 relais are working fine on the board even when I switch the cables (auger vs. fan).

It looks like GPIO14 is not providing any output at all, neither high or low.

 

Settings.json is attached, 

 

But where do I find the platform configuration settings?

 



 

Von: nebhead ***@***.***> 
Gesendet: Montag, 25. November 2024 17:36
An: nebhead/PiFire ***@***.***>
Cc: thomasstrach ***@***.***>; Author ***@***.***>
Betreff: Re: [nebhead/PiFire] Problem after SW update and re-install (Issue #207)

 

Are you now on the latest PiFire (main branch)? v1.8.x?

In the configuration wizard, are you selecting the 2.00a PCB?

image.png (view on web) <https://github.com/user-attachments/assets/63b85e16-1315-480e-9039-3148020839e0> 

Can get the settings.json file (let me know if you need help getting this) and post the platform configuration section? It should look something like this (yours will have different values):

  "platform": {
    "buttonslevel": "HIGH",
    "current": "custom",
    "dc_fan": true,
    "devices": {
      "display": {
        "dc": 24,
        "led": 5,
        "rst": 25
      },
      "distance": {
        "echo": 27,
        "trig": 23
      },
      "input": {
        "down_dt": 20,
        "enter_sw": 21,
        "up_clk": 16
      }
    },
    "inputs": {
      "selector": 17,
      "shutdown": 17
    },
    "outputs": {
      "auger": 14,
      "dc_fan": 26,
      "fan": 15,
      "igniter": 18,
      "power": 4,
      "pwm": 13
    },
    "real_hw": false,
    "standalone": true,
    "system": {
      "1WIRE": 6,
      "SPI0": {
        "CE0": 8,
        "CE1": 7
      }
    },
    "system_type": "prototype",
    "triggerlevel": "HIGH"
  }

**Comment by nebhead** [comment]
>  Settings.json is attached, But where do I find the platform

Unfortunately the settings.json did not come across in GitHub.  If you look at the file, you should see a section that says: "platform".

**Comment by thomasstrach** [comment]
Ah, now I got it…

 

"platform": {

    "buttonslevel": "HIGH",

    "current": "pcb_2.00a",

    "dc_fan": false,

    "devices": {

      "display": {

        "dc": 24,

        "led": 5,

        "rst": 25

      },

      "distance": {

        "echo": 27,

        "trig": 23

      },

      "input": {

        "down_dt": 20,

        "enter_sw": 21,

        "up_clk": 16

      }

    },

    "inputs": {

      "selector": 17,

      "shutdown": null

    },

    "outputs": {

      "auger": 14,

      "dc_fan": null,

      "fan": 15,

      "igniter": 18,

      "power": 4,

      "pwm": null

    },

    "real_hw": true,

    "standalone": true,

    "system": {

      "1WIRE": null,

      "SPI0": {

        "CE0": 8,

        "CE1": 7

      }

    },

    "system_type": "raspberry_pi_all",

    "triggerlevel": "HIGH"

  },

  "probe_settings": {

    "probe_map": {

      "probe_devices": [

        {

          "config": {

            "ADC0_rd": "10000",

            "ADC1_rd": "10000",

            "ADC2_rd": "10000",

            "ADC3_rd": "10000",

            "i2c_bus_addr": "0x48",

            "voltage_ref": "3.28"

          },

          "device": "ADS1115",

          "module": "ads1115_adafruit",

          "ports": [

            "ADC0",

            "ADC1",

            "ADC2",

            "ADC3"

          ]

        }

      ],

      "probe_info": [

        {

          "device": "ADS1115",

          "enabled": true,

          "label": "Grill",

          "name": "Grill",

          "port": "ADC0",

          "profile": {

            "A": 0.05966017913127897,

            "B": -0.01048654943772497,

            "C": 4.987389532180097e-05,

            "id": "99b8f02d-233d-11ee-a7a2-e5396c02c5fd",

            "name": "PT-1000-Ideal"

          },

          "type": "Primary"

        },

        {

          "device": "ADS1115",

          "enabled": true,

          "label": "Probe1",

          "name": "Probe-1",

          "port": "ADC1",

          "profile": {

            "A": 0.08349559509913372,

            "B": -0.015417214989461945,

            "C": 8.10020549005308e-05,

            "id": "04204563-2335-11ee-9a44-e5396c02c605",

            "name": "PT-1000-OEM-2023"

          },

          "type": "Food"

        },

        {

          "device": "ADS1115",

          "enabled": true,

          "label": "Probe2",

          "name": "Probe-2",

          "port": "ADC2",

          "profile": {

            "A": 0.08349559509913372,

            "B": -0.015417214989461945,

            "C": 8.10020549005308e-05,

            "id": "04204563-2335-11ee-9a44-e5396c02c605",

            "name": "PT-1000-OEM-2023"

          },

          "type": "Food"

        }

      ]

    },

  "probe_profiles": {

      "04204563-2335-11ee-9a44-e5396c02c605": {

        "A": 0.08349559509913372,

        "B": -0.015417214989461945,

        "C": 8.10020549005308e-05,

        "id": "04204563-2335-11ee-9a44-e5396c02c605",

        "name": "PT-1000-OEM-2023"

      },

      "99b8f02d-233d-11ee-a7a2-e5396c02c5fd": {

        "A": 0.05966017913127897,

        "B": -0.01048654943772497,

        "C": 4.987389532180097e-05,

        "id": "99b8f02d-233d-11ee-a7a2-e5396c02c5fd",

        "name": "PT-1000-Ideal"

      },

      "ET73-HM": {

        "A": 0.00024723753,

        "B": 0.00023402251,

        "C": 1.3879768e-07,

        "id": "ET73-HM",

        "name": "ET-73-Heatermeter"

      },

      "ET73-SP": {

        "A": 0.00023067434,

        "B": 0.00023696596,

        "C": 1.2636414e-07,

        "id": "ET73-SP",

        "name": "ET-73-skyeperry1"

      },

      "PT-1000-OEM": {

        "A": 0.04136906456,

        "B": -0.00677987613,

        "C": 2.760294589e-05,

        "id": "PT-1000-OEM",

        "name": "PT-1000-Grill-Probe-OEM"

      },

      "PT-1000-PiFire": {

        "A": 0.05469905897345206,

        "B": -0.009473055040089443,

        "C": 4.3768560703857386e-05,

        "id": "PT-1000-PiFire",

        "name": "PT-1000-Grill-Probe-PiFire"

      },

      "TWPS00": {

        "A": 0.00073431401,

        "B": 0.0002157437,

        "C": 9.515686e-08,

        "id": "TWPS00",

        "name": "Thermoworks-Pro-Series-HeaterMeter"

      },

      "iGrill-HM": {

        "A": 0.0007739251279,

        "B": 0.0002088025997,

        "C": 1.154400438e-07,

        "id": "iGrill-HM",

        "name": "iGrill-Heatermeter"

      }

    }

  },

  "pwm": {

    "frequency": 25000,

    "max_duty_cycle": 100,

    "min_duty_cycle": 20,

    "profiles": [

      {

        "duty_cycle": 20

      },

      {

        "duty_cycle": 35

      },

      {

        "duty_cycle": 50

      },

      {

        "duty_cycle": 75

      },

      {

        "duty_cycle": 100

      }

    ],

    "pwm_control": false,

    "temp_range_list": [

      3,

      7,

      10,

      15

    ],

    "update_time": 10

  },

  "recipe": {

    "probe_map": {

      "food": [

        "Probe1",

        "Probe2",

        "Probe3"

      ],

      "primary": "Grill"

    }

  },

  "safety": {

    "maxstartuptemp": 45,

    "maxtemp": 300,

    "minstartuptemp": 1,

    "reigniteretries": 1,

    "startup_check": true

  },

  "shutdown": {

    "auto_power_off": false,

    "shutdown_duration": 240

  },

  "smoke_plus": {

    "duty_cycle": 75,

    "enabled": false,

    "fan_ramp": false,

    "max_temp": 102,

    "min_temp": 70,

    "off_time": 5,

    "on_time": 5

  },

  "startup": {

    "duration": 240,

    "prime_on_startup": 0,

    "smartstart": {

      "enabled": false,

      "exit_temp": 46,

      "profiles": [

        {

          "augerontime": 15,

          "p_mode": 0,

          "startuptime": 360

        },

        {

          "augerontime": 15,

          "p_mode": 1,

          "startuptime": 360

        },

        {

          "augerontime": 15,

          "p_mode": 3,

          "startuptime": 240

        },

        {

          "augerontime": 15,

          "p_mode": 5,

          "startuptime": 240

        }

      ],

      "temp_range_list": [

        15,

        25,

        30

      ]

    },

    "start_to_mode": {

      "after_startup_mode": "Smoke",

      "primary_setpoint": 165

    },

    "startup_exit_temp": -17

  },

  "versions": {

    "build": 36,

    "cookfile": "1.5.0",

    "recipe": "1.0.0",

    "server": "1.8.8"

  }

}

 

Von: nebhead ***@***.***> 
Gesendet: Montag, 25. November 2024 19:56
An: nebhead/PiFire ***@***.***>
Cc: thomasstrach ***@***.***>; Author ***@***.***>
Betreff: Re: [nebhead/PiFire] Problem after SW update and re-install (Issue #207)

 

Settings.json is attached, But where do I find the platform

Unfortunately the settings.json did not come across in GitHub. If you look at the file, you should see a section that says: "platform".

**Comment by nebhead** [comment]
That all looks OK.  Is there a possible issue with your relay?   Or the wiring from the relay header?  Do you have a multimeter?  Can you test the relay header is outputting high or low when expected?

**Comment by thomasstrach** [comment]
Well it is really strange. In the end I used the manual config with GPIO4 instead GPIO14 for the auger and changed the input cables at the relais card.

The power relais is not working now on GPIO14 but GPIO4 is turning the auger on.

Encoder switch is not working now, will have a look on this later on.

 

Von: nebhead ***@***.***> 
Gesendet: Montag, 25. November 2024 20:30
An: nebhead/PiFire ***@***.***>
Cc: thomasstrach ***@***.***>; Author ***@***.***>
Betreff: Re: [nebhead/PiFire] Problem after SW update and re-install (Issue #207)

 

That all looks OK. Is there a possible issue with your relay? Or the wiring from the relay header? Do you have a multimeter? Can you test the relay header is outputting high or low when expected?

**Comment by nebhead** [comment]
This pin is also used as a UART pin if configured, so hopefully that didn't get turned on be default or anything.  Normally this is not configured for UART.   You can check your /boot/firmware/config.txt to see if there is any lines that are enabling UART.

**Comment by nebhead** [comment]
OK, that all looks fine.  Well, except for the PWM pin being activated.  I'd recommend adding a # in front of that line to ensure PWM is not enabled.  Assuming you are not using a DC Fan on this build.  

So when you measure voltage of GPIO14, are you changing the output with manual mode?  Does it still not switch?  That might indicate that the GPIO14 is damaged/not working.  What we might be able to do is to utilize another spare GPIO to the relay instead.  Basically tie another of the GPIO's from the AUX header that you are not currently using - we can set the settings.json appropriately to utilize the other GPIO.

**Comment by thomasstrach** [comment]
First of all I am really mad about myself, why did I changed anything on a proper running system… ☹

 

Maybe it’s a better idea to downgrade to an older version?

 

Looking at the /boot/firmware/config.txt file, where to put the #?

Do you mean it like this?

 

enable_uart=0

dtparam=act_led_trigger=actpwr

# dtoverlay=pwm,func=4,pin=13  # Modified by PiFire Board Configuration Utility

 

Meanwhile the controller is working remotely with the manual setup and using GPIO4 for the auger instead of GPIO14 and it keeps the set temperature/mode fine.

 

I am using the ili9341 with the rotary encoder, this encoder is not working at all.

No matter which of the 2 encoders I am choosing during setup wizard.



 

The display is working after startup until I have changed the “set temp” or “workmode” several times. 

After doing this changes the display turns blank, just shining bright, the webinterface and the smoker itself continues running.

Once I noticed that with a blank display the notification for running out of pellets continues sending alarms despite I filled up the pellets and the webinterface shows 100%.

 

When I push the stop button on the web interface the system stops immediately without the 240 sec. fan cool down time. Is this behavior ok?

During startup I am missing the prime functionality before ignite function. 

Is this available by starting via the web interface?

 

 

 

 

 

 

 

Von: nebhead ***@***.***> 
Gesendet: Dienstag, 26. November 2024 18:01
An: nebhead/PiFire ***@***.***>
Cc: thomasstrach ***@***.***>; Author ***@***.***>
Betreff: Re: [nebhead/PiFire] Problem after SW update and re-install (Issue #207)

 

OK, that all looks fine. Well, except for the PWM pin being activated. I'd recommend adding a # in front of that line to ensure PWM is not enabled. Assuming you are not using a DC Fan on this build.

So when you measure voltage of GPIO14, are you changing the output with manual mode? Does it still not switch? That might indicate that the GPIO14 is damaged/not working. What we might be able to do is to utilize another spare GPIO to the relay instead. Basically tie another of the GPIO's from the AUX header that you are not currently using - we can set the settings.json appropriately to utilize the other GPIO.

**Comment by thomasstrach** [comment]
BTW. I found the Prime and Start functionality on the web interface!

 

Von: ***@***.*** ***@***.***> 
Gesendet: Mittwoch, 27. November 2024 13:29
An: 'nebhead/PiFire' ***@***.***>
Betreff: AW: [nebhead/PiFire] Problem after SW update and re-install (Issue #207)

 

First of all I am really mad about myself, why did I changed anything on a proper running system… ☹

 

Maybe it’s a better idea to downgrade to an older version?

 

Looking at the /boot/firmware/config.txt file, where to put the #?

Do you mean it like this?

 

enable_uart=0

dtparam=act_led_trigger=actpwr

# dtoverlay=pwm,func=4,pin=13  # Modified by PiFire Board Configuration Utility

 

Meanwhile the controller is working remotely with the manual setup and using GPIO4 for the auger instead of GPIO14 and it keeps the set temperature/mode fine.

 

I am using the ili9341 with the rotary encoder, this encoder is not working at all.

No matter which of the 2 encoders I am choosing during setup wizard.



 

The display is working after startup until I have changed the “set temp” or “workmode” several times. 

After doing this changes the display turns blank, just shining bright, the webinterface and the smoker itself continues running.

Once I noticed that with a blank display the notification for running out of pellets continues sending alarms despite I filled up the pellets and the webinterface shows 100%.

 

When I push the stop button on the web interface the system stops immediately without the 240 sec. fan cool down time. Is this behavior ok?

During startup I am missing the prime functionality before ignite function. 

Is this available by starting via the web interface?

 

 

 

 

 

 

 

Von: nebhead ***@***.*** ***@***.***> > 
Gesendet: Dienstag, 26. November 2024 18:01
An: nebhead/PiFire ***@***.*** ***@***.***> >
Cc: thomasstrach ***@***.*** ***@***.***> >; Author ***@***.*** ***@***.***> >
Betreff: Re: [nebhead/PiFire] Problem after SW update and re-install (Issue #207)

 

OK, that all looks fine. Well, except for the PWM pin being activated. I'd recommend adding a # in front of that line to ensure PWM is not enabled. Assuming you are not using a DC Fan on this build.

So when you measure voltage of GPIO14, are you changing the output with manual mode? Does it still not switch? That might indicate that the GPIO14 is damaged/not working. What we might be able to do is to utilize another spare GPIO to the relay instead. Basically tie another of the GPIO's from the AUX header that you are not currently using - we can set the settings.json appropriately to utilize the other GPIO.

**Comment by nebhead** [comment]
> First of all I am really mad about myself, why did I changed anything on a proper running system… ☹ Maybe it’s a better idea to downgrade to an older version? 

Don't beat yourself up.  We'll figure this out.  You can try to downgrade, but I'm willing to bet you're going to have issues.  

> Looking at the /boot/firmware/config.txt file, where to put the #? Do you mean it like this? 
> enable_uart=0 
> dtparam=act_led_trigger=actpwr 
> # dtoverlay=pwm,func=4,pin=13 # Modified by PiFire Board Configuration Utility 

Yep, perfect.  

Do you see any other lines in there, for example for 1-Wire that are enabled?   We definitely want to disable 1-Wire and have had reports of the new version turning it on by mistake. 

> Meanwhile the controller is working remotely with the manual setup and using GPIO4 for the auger instead of GPIO14 and it keeps the set temperature/mode fine. 

So, that's encouraging.  Still strange that the GPIO14 is misbehaving.  Do you have a different Pi by any chance?  We could not even hook it up to the board, and install PiFire, just to test if GPIO14 behaves differently.  

> I am using the ili9341 with the rotary encoder, this encoder is not working at all. No matter which of the 2 encoders I am choosing during setup wizard. The display is working after startup until I have changed the “set temp” or “workmode” several times. After doing this changes the display turns blank, just shining bright, the webinterface and the smoker itself continues running. 

Can you take a screenshot of the one that you are using the configuration wizard?   It sounds like it might be a config issue that I've seen before.  Also, I've seen this with loose wiring to the display.  Unless this is consistent, there are a few things that can be touchy here.  

> Once I noticed that with a blank display the notification for running out of pellets continues sending alarms despite I filled up the pellets and the webinterface shows 100%. 

This might be an actual bug.  I'll look into this. 

> When I push the stop button on the web interface the system stops immediately without the 240 sec. fan cool down time. Is this behavior ok? 

Yes, the stop button will cause it to stop immediately where as the little finish flag will go through a shutdown cycle for 240s.  The finish flag only shows up after you exit startup mode.  

> During startup I am missing the prime functionality before ignite function. Is this available by starting via the web interface? 

Looks like you found it!

**Comment by thomasstrach** [comment]
Thanks for your effort with my problems, really very much appreciated!

 

See my comments below:

 

 

Von: nebhead ***@***.***> 
Gesendet: Mittwoch, 27. November 2024 18:09
An: nebhead/PiFire ***@***.***>
Cc: thomasstrach ***@***.***>; Author ***@***.***>
Betreff: Re: [nebhead/PiFire] Problem after SW update and re-install (Issue #207)

 

First of all I am really mad about myself, why did I changed anything on a proper running system… ☹ Maybe it’s a better idea to downgrade to an older version?

Don't beat yourself up. We'll figure this out. You can try to downgrade, but I'm willing to bet you're going to have issues.

Ok, I will continue with this version and hope you can help me to get it fixed.

Looking at the /boot/firmware/config.txt file, where to put the #? Do you mean it like this?
enable_uart=0
dtparam=act_led_trigger=actpwr


dtoverlay=pwm,func=4,pin=13 # Modified by PiFire Board Configuration Utility


Yep, perfect.

Just implementent the change, will have to test it.

Do you see any other lines in there, for example for 1-Wire that are enabled? We definitely want to disable 1-Wire and have had reports of the new version turning it on by mistake.

I cannot find anything in this file regarding 1-wire.

Meanwhile the controller is working remotely with the manual setup and using GPIO4 for the auger instead of GPIO14 and it keeps the set temperature/mode fine.

So, that's encouraging. Still strange that the GPIO14 is misbehaving. Do you have a different Pi by any chance? We could not even hook it up to the board, and install PiFire, just to test if GPIO14 behaves differently.

I have just ordered another raspberry  zero 2W to test this out. Will take some days…

I am using the ili9341 with the rotary encoder, this encoder is not working at all. No matter which of the 2 encoders I am choosing during setup wizard. The display is working after startup until I have changed the “set temp” or “workmode” several times. After doing this changes the display turns blank, just shining bright, the webinterface and the smoker itself continues running.

Can you take a screenshot of the one that you are using the configuration wizard? It sounds like it might be a config issue that I've seen before. Also, I've seen this with loose wiring to the display. Unless this is consistent, there are a few things that can be touchy here.

I used GPIO 20/21/16 for the button Down/Enter/Buttom up config (pre-set), that’s where my encoder is connected.



I have tried out both selections for the encoder



 

Once I noticed that with a blank display the notification for running out of pellets continues sending alarms despite I filled up the pellets and the webinterface shows 100%.

This might be an actual bug. I'll look into this.

When I push the stop button on the web interface the system stops immediately without the 240 sec. fan cool down time. Is this behavior ok?

Yes, the stop button will cause it to stop immediately where as the little finish flag will go through a shutdown cycle for 240s. The finish flag only shows up after you exit startup mode.

Ah, I only used the shutdown on the display with the rotary encoder before.

During startup I am missing the prime functionality before ignite function. Is this available by starting via the web interface?

Looks like you found it!

Yes, I used the display with encoder before for startup.

**Comment by nebhead** [comment]
> I have just ordered another raspberry  zero 2W to test this out. Will take some days…

This is great - it should help us to understand if what we are seeing is a hardware problem with the existing Pi.

**Comment by thomasstrach** [comment]
Just received the controller and things have turned around.

After formatting the sd card, now the WIFI was connected automatically, that was not happening before with several attemps.

All is running fine, no problems anymore.

Display is working, encoder and all GPIOs.

I will try again when I have time with old Pi, maybe the SD card and/or the Pi is wrong.

Thanks a lot for your patience and support!

 

Von: nebhead ***@***.***> 
Gesendet: Donnerstag, 28. November 2024 17:35
An: nebhead/PiFire ***@***.***>
Cc: thomasstrach ***@***.***>; Author ***@***.***>
Betreff: Re: [nebhead/PiFire] Problem after SW update and re-install (Issue #207)

 

I have just ordered another raspberry zero 2W to test this out. Will take some days…

This is great - it should help us to understand if what we are seeing is a hardware problem with the existing Pi.

**Comment by nebhead** [comment]
Excellent news!  You are very welcome.  Hope all is well from here on out.
