### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by ryanmurray** [nebhead/PiFire#78]
So got my pellet hopper sensor installed started tweaking numbers rebooted and now im in infinite loop

log from control
efault_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/pi/pifire/control.py", line 1253, in <module>
    pelletdb = ReadPelletDB()
  File "/home/pi/pifire/common.py", line 497, in ReadPelletDB
    pelletdb_struct = json.loads(json_data_string)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by ryanmurray** [comment]
tried unplugging sensor but that didnt help either

**Comment by ryanmurray** [comment]
No sure what happened nuked the pifire folder and restarted

**Comment by nebhead** [comment]
Looks like your pelletdb.json got corrupted somehow.  Maybe try deleting that file (it should get automatically recreated) and rebooting.

**Comment by nebhead** [comment]
Also, if you could tell me which pellet sensor you are using, that might help. 

BTW - if you remove the pellet sensor, and still have the system configured to use the hardware pellet sensor it will probably crash.  I really need to incorporate some error checking for these things.

**Comment by ryanmurray** [comment]
> Also, if you could tell me which pellet sensor you are using, that might help. 
> 
> BTW - if you remove the pellet sensor, and still have the system configured to use the hardware pellet sensor it will probably crash.  I really need to incorporate some error checking for these things. 

I'm using the vx one reinstalling got me back up. Next time I will nuke pellet database. File was blank when I looked in it so making more sense

**Comment by nebhead** [comment]
Cool, glad you got it back up and running.  Hopefully the sensor is working OK too.
